-- 2022년 1월의 도서 판매 데이터를 기준
-- 카테고리 별 매출액(판매량 * 판매가)을 구하여 리스트로 출력

-- BOOK_SALES테이블의  BOOK_ID와 BOOK테이블의 BOOK_ID를 조인한다. AS SALE
-- 서브 쿼리를 사용하여 BOOK_SALES의 BOOK_ID를 그룹화 한 뒤, SUM(SALES)을 구하고 * 
SELECT B.AUTHOR_ID, AU.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) as TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR AS AU ON B.AUTHOR_ID = AU.AUTHOR_ID
WHERE BS.SALES_DATE LIKE '2022-01-%'
GROUP BY B.AUTHOR_ID, AU.AUTHOR_NAME, B.CATEGORY

ORDER BY B.AUTHOR_ID, CATEGORY DESC;
