-- USER_INFO 회원 정보 테이블 (회원 ID, 성별, 나이, 가입일)
-- ONLINE_SALE 온라인 상품 판매 정보 테이블 (온라인 상품 판매 ID, 회원 ID, 상품 ID, 판매량, 판매일)

-- 년, 월, 성별 별로 상품을 구매한 '회원수' 집계

SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE AS OS
LEFT JOIN USER_INFO AS UI ON OS.USER_ID = UI.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER


