-- 아이스크림 총 주문량 + 상반기 아이스크림의 총 주문량의 값이 큰 순서 상위 3개
SELECT H.FLAVOR
FROM FIRST_HALF AS H
LEFT JOIN (SELECT FLAVOR, TOTAL_ORDER
           FROM JULY ) 
           AS J ON H.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY (H.TOTAL_ORDER + SUM(J.TOTAL_ORDER)) DESC
LIMIT 3