-- 1. WHERE를 통해서 완료된 중고 거래 금액이 70만원 이상인 회원을 조회한다.
-- 2. 총 거래 금액 계산 GROUP BY WRITER_ID 이후 SUM(PRICE)
-- 3. WRITER_ID와 USER_ID를 JOIN 후 USER_ID와 NICKNAME을 가져온다.
SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_USER as U
JOIN USED_GOODS_BOARD as B ON U.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;