/*2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서
해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력하는 SQL문을 작성해주세요.*/

SELECT MONTH(START_DATE) AS MONTH,  CAR_ID,  COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022
    AND MONTH(START_DATE) BETWEEN 8 AND 10
    AND CAR_ID IN (
                    SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE YEAR(START_DATE) = 2022
                    AND MONTH(START_DATE) BETWEEN 8 AND 10
                    GROUP BY CAR_ID
                    HAVING COUNT(*) >= 5)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC;