-- 코드를 입력하세요
SELECT INFO.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS INGREDIENT_TYPE
FROM FIRST_HALF HALF
JOIN ICECREAM_INFO INFO ON HALF.FLAVOR = INFO.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE


/*
FIRST_HALF = 성분 정보 
ICECREAM_INFO = 아이스크림 정보
주 성분이 sugar_based인 총 주문량 sum(TOTAL_ORDER)
주 성분이 fruit_based인 총 주문량

FIRST_HALF FLAVOR이 (SELECT FLAVOR )
ICECREAM_INFO의 타입이 sugar_based인 FLAVOR을 구해서


*/